server:
  port: 8001
spring:
  application:
    name: eruekaclient1
eureka:
  client:
      service-url:
        defaultZone:  http://localhost:7001/eureka/,http://localhost:7000/eureka/
      instance:
        hostname: localhost