server:
  port: 7000
spring:
  application:
    name: eurekServer1
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
