server:
  port: 7001
spring:
  application:
    name: eurekServer2
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7000/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost